spring:
  application:
    name: finance-tracker

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/finance
    username: user
    password: tytRib-myksy7-rupmog

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect


