INSERT INTO category (id, name)
VALUES  (1, 'Housing'),
        (2, 'Utilities'),
        (3, 'Groceries'),
        (4, 'Dining out/ takeout'),
        (5, 'Transportation'),
        (6, 'Insurance'),
        (7, 'Healthcare'),
        (8, 'Personal Care'),
        (9, 'Clothing & Shoes'),
        (10, 'Child Care'),
        (11, 'Pets'),
        (12, 'Subscriptions'),
        (13, 'Entertainment'),
        (14, 'Travel'),
        (15, 'Education');
