ALTER TABLE expenses
    DROP FOREIGN KEY FK_EXPENSES_ON_USER;

ALTER TABLE expenses
    ADD CONSTRAINT FK_EXPENSES_ON_USER
        FOREIGN KEY (user_id) REFERENCES app_user(id)
        ON DELETE CASCADE;

ALTER TABLE budget
    DROP FOREIGN KEY FK_BUDGET_ON_USER;

ALTER TABLE budget
    ADD CONSTRAINT FK_BUDGET_ON_USER
        FOREIGN KEY (user_id) REFERENCES app_user (id)
        ON DELETE CASCADE;

ALTER TABLE account_info
    DROP FOREIGN KEY FK_ACCOUNT_INFO_ON_USER;

ALTER TABLE account_info
    ADD CONSTRAINT FK_ACCOUNT_INFO_ON_USER
        FOREIGN KEY (user_id) REFERENCES app_user (id)
        ON DELETE CASCADE;